OrdererOrgs:
  - Name: OrdererOrg
    Domain: orderer-org
    CommonName: orderer-org
    Specs:
      - Hostname: orderer0
        CommonName: "{{.Hostname}}"

PeerOrgs:
  - Name: CourtOrg
    Domain: court-org
    Specs:
      - Hostname: court-peer
        CommonName: "{{.Hostname}}"

  - Name: PrisonOrg
    Domain: prison-org
    Specs:
      - Hostname: prison-peer
        CommonName: "{{.Hostname}}"

  - Name: InvestigationOrg
    Domain: investigation-org
    Specs:
      - Hostname: investigation-peer
        CommonName: "{{.Hostname}}"

  - Name: LawEnforcementOrg
    Domain: law-enforcement-org
    Specs:
      - Hostname: law-enforcement-peer
        CommonName: "{{.Hostname}}"
